CREATE DATABASE CarFilterDB

GO
USE CarFilterDB

GO
CREATE TABLE Car(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Name] nvarchar(30) not null,
[BrandId] INT FOREIGN KEY REFERENCES Brand(Id) ON DELETE CASCADE,
[TypeId] INT FOREIGN KEY REFERENCES CarType(Id) ON DELETE CASCADE,
)

CREATE TABLE Brand(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Name] NVARCHAR(30) NOT NULL,
UNIQUE(Name)
)
CREATE TABLE CarType(
Id INT PRIMARY KEY Identity(1,1) NOT NULL,
[Name] NVARCHAR(30) NOT NULL,
)

ALTER TABLE Car
ALTER COLUMN Price Money NOT NULL

ALTER TABLE Car
ADD Kilometers Money NOT NULL

ALTER TABLE Car
ADD [Year] int NOT NULL

ALTER TABLE Car
ADD [Color] NVARCHAR(30) NOT NULL

ALTER TABLE Car
ADD [IsNew] BIT  NOT NULL

INSERT INTO CarType([Name]) VALUES('Jeep'),('Sedan')
INSERT INTO Brand([Name]) VALUES('BMW'),('Mercedes')
INSERT INTO Car([Name],[Year],[Price],[Kilometers],[Color],[IsNew],[BrandId],[TypeId]) VALUES('x5',2019,70000,100,'Black',1,1,1)